# Generated by Django 4.2.6 on 2023-10-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelCusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='account_number',
            field=models.BigIntegerField(),
        ),
    ]
