# Generated by Django 4.2.6 on 2023-10-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntelCusApp', '0002_alter_maintable_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersserviceprovider',
            old_name='company_name',
            new_name='service_provider_name',
        ),
    ]
